name: LinkYourDiscord
version: 1.1
api-version: 1.13
main: com.linkyourdiscord.LinkYourDiscord
author: AminJuPeter
description: A plugin to link Minecraft accounts to Discord accounts
commands:
  discord:
    description: Generates a linking code for your Discord account.
    usage: /discord
  unlink:
    description: Unlink a Minecraft account from Discord.
    usage: /unlink <player>
    permission: linkyourdiscord.admin
permissions:
  linkyourdiscord.admin:
    description: Allows admin to unlink Discord accounts.
    default: op